#!/usr/bin/env python3
"""
Sync AI tool configs from .claude/ (source of truth).

    python sync-ai-configs.py

Sources:
    .claude/shared.md     — roster, layout, pipeline, critical rules (one copy)
    .claude/agents/*.md   — role-only stubs (not shared.md)

Generates:
    .cursor/rules/*.mdc
    .github/copilot-instructions.md
    AGENTS.md
    .windsurfrules
    .agents/skills/<name>/SKILL.md
"""

import re
from pathlib import Path

ROOT = Path(__file__).parent
CLAUDE = ROOT / ".claude"
GENERATED_HEADER = (
    "<!-- AUTO-GENERATED by sync-ai-configs.py — DO NOT EDIT. "
    "Source: .claude/shared.md + .claude/agents/ -->\n\n"
)


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"  wrote {path.relative_to(ROOT)}")


def strip_frontmatter(text: str) -> tuple[dict, str]:
    if not text.startswith("---"):
        return {}, text
    end = text.index("---", 3)
    fm_block = text[3:end].strip()
    body = text[end + 3 :].strip()
    fm: dict = {}
    for line in fm_block.splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            fm[k.strip()] = v.strip()
    return fm, body


def clean_body(body: str) -> str:
    """Drop Claude-only 'Start by reading' fences; keep the shared.md pointer."""
    return re.sub(
        r"Start by reading[^\n]*\n+```\n[^`]+```\n*",
        "",
        body,
        flags=re.DOTALL,
    ).strip()


SHARED = read(CLAUDE / "shared.md").strip()
if not SHARED:
    raise SystemExit("missing .claude/shared.md")

agents: dict[str, tuple[dict, str]] = {}
for f in sorted((CLAUDE / "agents").glob("*.md")):
    if f.stem.startswith("_"):
        continue
    fm, body = strip_frontmatter(read(f))
    agents[f.stem] = (fm, body)


def mdc(description: str, body: str, always: bool = False, globs: list[str] | None = None) -> str:
    globs_line = ""
    if globs:
        patterns = ", ".join(f'"{g}"' for g in globs)
        globs_line = f"\nglobs: [{patterns}]"
    apply = "true" if always else "false"
    return (
        f"---\ndescription: {description}\nalwaysApply: {apply}{globs_line}\n---\n\n"
        f"{GENERATED_HEADER}{body.strip()}\n"
    )


cursor_rules = {
    "00-project.mdc": mdc(
        description="Shared Polygon problem-generator rules (roster, layout, pipeline)",
        always=True,
        body=SHARED,
    ),
    "01-statement.mdc": mdc(
        description="Role: statement-agent",
        globs=["**/statement*.tex", "**/tutorial*.tex", "**/raw.tex"],
        body=clean_body(agents["statement-agent"][1]),
    ),
    "02-validator.mdc": mdc(
        description="Role: validator-agent",
        globs=["**/validator.cpp"],
        body=clean_body(agents["validator-agent"][1]),
    ),
    "03-checker.mdc": mdc(
        description="Role: checker-agent",
        globs=["**/checker.cpp"],
        body=clean_body(agents["checker-agent"][1]),
    ),
    "04-solutions.mdc": mdc(
        description="Role: solutions-agent",
        globs=["**/solutions/**/*.cpp", "**/solutions/**/*.java"],
        body=clean_body(agents["solutions-agent"][1]),
    ),
    "05-generator.mdc": mdc(
        description="Role: generator-agent",
        globs=["**/generators/**/*.cpp"],
        body=clean_body(agents["generator-agent"][1]),
    ),
    "06-review.mdc": mdc(
        description="Role: reviewer-agent",
        body=clean_body(agents["reviewer-agent"][1]),
    ),
    "07-interactor.mdc": mdc(
        description="Role: interactor-agent",
        globs=["**/interactor.cpp"],
        body=clean_body(agents["interactor-agent"][1]),
    ),
}

for filename, content in cursor_rules.items():
    write(ROOT / ".cursor" / "rules" / filename, content)

write(
    ROOT / ".github" / "copilot-instructions.md",
    GENERATED_HEADER + SHARED + "\n\nRole details live in `.claude/agents/`.\n",
)

write(
    ROOT / ".windsurfrules",
    GENERATED_HEADER + SHARED + "\n\nRole details live in `.claude/agents/`.\n",
)

role_sections = ""
for stem, (fm, body) in agents.items():
    role_sections += (
        f"### `{stem}`\n\n> {fm.get('description', '')}\n\n{clean_body(body)}\n\n---\n\n"
    )

write(
    ROOT / "AGENTS.md",
    GENERATED_HEADER
    + SHARED
    + "\n\n## Role contracts\n\n"
    + role_sections,
)


def skill_md(name: str, description: str, body: str) -> str:
    return (
        f"---\nname: {name}\ndescription: {description}\n---\n\n"
        f"{GENERATED_HEADER}Read `.claude/shared.md` first.\n\n{body.strip()}\n"
    )


skills_dir = ROOT / ".agents" / "skills"
for stem, (fm, body) in agents.items():
    write(
        skills_dir / stem / "SKILL.md",
        skill_md(stem, fm.get("description", ""), clean_body(body)),
    )

print("\nDone.")
print("  shared: .claude/shared.md")
print(f"  .cursor/rules/           ({len(cursor_rules)} rules)")
print("  .github/copilot-instructions.md")
print("  AGENTS.md")
print("  .windsurfrules")
print(f"  .agents/skills/          ({len(agents)} skills)")
